In [2]:
from dotenv import load_dotenv
import os

In [3]:
load_dotenv("../.env") 
MONGO_URI = os.getenv("MONGO_URI")
print(MONGO_URI[:10] + "...")

mongodb+sr...

In [4]:
from pymongo import MongoClient
import pandas as pd
client = MongoClient(MONGO_URI)
db = client["veille_media"]
collection = db["articles"]
data = list(collection.find())
df = pd.DataFrame(data)

df.head()

,_id,id_article,source,titre,date_publication,contenu,url,categorie,sentiment,source_type,created_at,sentiment_score
0,696f6450803a3bd1d5076f9f,https://www.madagascar-tribune.com/Conjoncture...,https://www.madagascar-tribune.com/spip.php?pa...,Richard Ravalomanana et Marie Michelle Sahondr...,"Tue, 20 Jan 2026 08:36:32 +0300",Deux figures emblématiques du régime Rajoelina...,https://www.madagascar-tribune.com/Conjoncture...,politique,neutre,NaN,NaN,NaN
1,696f6450803a3bd1d5076fa0,https://www.madagascar-tribune.com/Senat-la-HC...,https://www.madagascar-tribune.com/spip.php?pa...,Sénat : la HCC confirme la fin du mandat et l'...,"Tue, 20 Jan 2026 08:31:21 +0300",La Haute Cour constitutionnelle (HCC) a offici...,https://www.madagascar-tribune.com/Senat-la-HC...,autre,neutre,NaN,NaN,NaN
2,696f6451803a3bd1d5076fa1,https://www.madagascar-tribune.com/103-signatu...,https://www.madagascar-tribune.com/spip.php?pa...,103 poids plume,"Mon, 19 Jan 2026 08:35:00 +0300",Lors d'« Assises des Partis Politiques » pour ...,https://www.madagascar-tribune.com/103-signatu...,autre,negatif,NaN,NaN,NaN
3,696f6451803a3bd1d5076fa2,https://www.madagascar-tribune.com/Concertatio...,https://www.madagascar-tribune.com/spip.php?pa...,Concertation nationale : le président de la Re...,"Mon, 19 Jan 2026 08:00:00 +0300",Le colonel Randrianarina est venu à la rescous...,https://www.madagascar-tribune.com/Concertatio...,politique,positif,NaN,NaN,NaN
4,696f6451803a3bd1d5076fa3,https://www.madagascar-tribune.com/Administrat...,https://www.madagascar-tribune.com/spip.php?pa...,Herintsalama Rajaonarivelo ferme la porte à un...,"Mon, 19 Jan 2026 07:00:00 +0300","Ce dimanche, devant des milliers de fidèles de...",https://www.madagascar-tribune.com/Administrat...,autre,neutre,NaN,NaN,NaN

In [5]:
print("Total articles:", len(df))
print(df.info())
print(df.isna().sum())

Total articles: 2005
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2005 entries, 0 to 2004
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   _id               2005 non-null   object
 1   id_article        2005 non-null   object
 2   source            2005 non-null   object
 3   titre             2005 non-null   object
 4   date_publication  1997 non-null   object
 5   contenu           2005 non-null   object
 6   url               2005 non-null   object
 7   categorie         2005 non-null   object
 8   sentiment         2005 non-null   object
 9   source_type       1078 non-null   object
 10  created_at        1078 non-null   object
 11  sentiment_score   0 non-null      float64
dtypes: float64(1), object(11)
memory usage: 188.1+ KB
None
_id                    0
id_article             0
source                 0
titre                  0
date_publication       8
contenu                0
url                    0
categorie              0
sentiment              0
source_type          927
created_at           927
sentiment_score     2005
dtype: int64

In [7]:
critical_cols = ["date_publication", "source_type", "created_at"]
df_anormal = df[df[critical_cols].isna().any(axis=1)]
print(df_anormal[["id_article"] + critical_cols])

                                            id_article  \
0    https://www.madagascar-tribune.com/Conjoncture...
1    https://www.madagascar-tribune.com/Senat-la-HC...
2    https://www.madagascar-tribune.com/103-signatu...
3    https://www.madagascar-tribune.com/Concertatio...
4    https://www.madagascar-tribune.com/Administrat...
..                                                 ...
922               https://lgdi-madagascar.com/?p=10797
923               https://lgdi-madagascar.com/?p=10793
924               https://lgdi-madagascar.com/?p=10791
925               https://lgdi-madagascar.com/?p=10789
926               https://lgdi-madagascar.com/?p=10787

                    date_publication source_type created_at
0    Tue, 20 Jan 2026 08:36:32 +0300         NaN        NaN
1    Tue, 20 Jan 2026 08:31:21 +0300         NaN        NaN
2    Mon, 19 Jan 2026 08:35:00 +0300         NaN        NaN
3    Mon, 19 Jan 2026 08:00:00 +0300         NaN        NaN
4    Mon, 19 Jan 2026 07:00:00 +0300         NaN        NaN
..                               ...         ...        ...
922              2026-01-26 19:23:00         NaN        NaN
923              2026-01-26 19:10:53         NaN        NaN
924              2026-01-26 19:02:49         NaN        NaN
925              2026-01-26 19:00:11         NaN        NaN
926              2026-01-26 18:57:03         NaN        NaN

[927 rows x 4 columns]

In [8]:
df_anormal

,_id,id_article,source,titre,date_publication,contenu,url,categorie,sentiment,source_type,created_at,sentiment_score
0,696f6450803a3bd1d5076f9f,https://www.madagascar-tribune.com/Conjoncture...,https://www.madagascar-tribune.com/spip.php?pa...,Richard Ravalomanana et Marie Michelle Sahondr...,"Tue, 20 Jan 2026 08:36:32 +0300",Deux figures emblématiques du régime Rajoelina...,https://www.madagascar-tribune.com/Conjoncture...,politique,neutre,NaN,NaN,NaN
1,696f6450803a3bd1d5076fa0,https://www.madagascar-tribune.com/Senat-la-HC...,https://www.madagascar-tribune.com/spip.php?pa...,Sénat : la HCC confirme la fin du mandat et l'...,"Tue, 20 Jan 2026 08:31:21 +0300",La Haute Cour constitutionnelle (HCC) a offici...,https://www.madagascar-tribune.com/Senat-la-HC...,autre,neutre,NaN,NaN,NaN
2,696f6451803a3bd1d5076fa1,https://www.madagascar-tribune.com/103-signatu...,https://www.madagascar-tribune.com/spip.php?pa...,103 poids plume,"Mon, 19 Jan 2026 08:35:00 +0300",Lors d'« Assises des Partis Politiques » pour ...,https://www.madagascar-tribune.com/103-signatu...,autre,negatif,NaN,NaN,NaN
3,696f6451803a3bd1d5076fa2,https://www.madagascar-tribune.com/Concertatio...,https://www.madagascar-tribune.com/spip.php?pa...,Concertation nationale : le président de la Re...,"Mon, 19 Jan 2026 08:00:00 +0300",Le colonel Randrianarina est venu à la rescous...,https://www.madagascar-tribune.com/Concertatio...,politique,positif,NaN,NaN,NaN
4,696f6451803a3bd1d5076fa3,https://www.madagascar-tribune.com/Administrat...,https://www.madagascar-tribune.com/spip.php?pa...,Herintsalama Rajaonarivelo ferme la porte à un...,"Mon, 19 Jan 2026 07:00:00 +0300","Ce dimanche, devant des milliers de fidèles de...",https://www.madagascar-tribune.com/Administrat...,autre,neutre,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
922,697b5033e1a5c1e5045b6bbb,https://lgdi-madagascar.com/?p=10797,https://lgdi-madagascar.com/feed/,Ravalomanana Richard : La Honte des Forces Armées,2026-01-26 19:23:00,"L’armée se forge dans l’honneur, la discipline...",https://lgdi-madagascar.com/2026/01/26/politiq...,autre,neutre,NaN,NaN,NaN
923,697b5033e1a5c1e5045b6bbc,https://lgdi-madagascar.com/?p=10793,https://lgdi-madagascar.com/feed/,« Tolérance zéro » face aux travaux mal exécut...,2026-01-26 19:10:53,L’annonce par le gouvernement d’une politique ...,https://lgdi-madagascar.com/2026/01/26/societe...,politique,neutre,NaN,NaN,NaN
924,697b5033e1a5c1e5045b6bbd,https://lgdi-madagascar.com/?p=10791,https://lgdi-madagascar.com/feed/,Madagascar : La refondation économique passe p...,2026-01-26 19:02:49,Madagascar ne souffre pas d’un déficit de pote...,https://lgdi-madagascar.com/2026/01/26/economi...,autre,neutre,NaN,NaN,NaN
925,697b5033e1a5c1e5045b6bbe,https://lgdi-madagascar.com/?p=10789,https://lgdi-madagascar.com/feed/,Fanavaozana hoe? Izao no isany:,2026-01-26 19:00:11,"Atsaharo ny fanararaotam-pahefana, amboary ny ...",https://lgdi-madagascar.com/2026/01/26/gazetin...,autre,neutre,NaN,NaN,NaN
926,697b5034e1a5c1e5045b6bbf,https://lgdi-madagascar.com/?p=10787,https://lgdi-madagascar.com/feed/,Fitantanam-pitondrana : Madagasikara sy Syrie ...,2026-01-26 18:57:03,Ankehitriny dia mitaky fifanarahana politika i...,https://lgdi-madagascar.com/2026/01/26/gazetin...,autre,neutre,NaN,NaN,NaN

In [9]:
import pandas as pd

df["date_publication"] = pd.to_datetime(
    df["date_publication"],
    errors="coerce",
    utc=True
)

In [10]:
df[df["date_publication"].isna()]

,_id,id_article,source,titre,date_publication,contenu,url,categorie,sentiment,source_type,created_at,sentiment_score
25,696f6b3b7a90c7b400bf72b9,"tag:blogger.com,1999:blog-4737517494033053260....",https://www.lexpress.mg/feeds/posts/default,POURSUITE JUDICIAIRE - Le général Ravalomanana...,NaT,L’ancien président du Sénat et l’ancienne mini...,https://www.lexpress.mg/2026/01/poursuite-judi...,politique,negatif,NaN,NaN,NaN
26,696f6b3b7a90c7b400bf72ba,"tag:blogger.com,1999:blog-4737517494033053260....",https://www.lexpress.mg/feeds/posts/default,CCI IVATO - Le colonel Randrianirina rassure l...,NaT,Le Chef de l’État a donné le coup d’envoi des ...,https://www.lexpress.mg/2026/01/cci-ivato-le-c...,politique,neutre,NaN,NaN,NaN
27,696f6b3b7a90c7b400bf72bb,"tag:blogger.com,1999:blog-4737517494033053260....",https://www.lexpress.mg/feeds/posts/default,TÉLÉCOMMUNICATIONS - Réforme législative en v...,NaT,Le gouvernement prépare un décret d’applicatio...,https://www.lexpress.mg/2026/01/telecommunicat...,politique,negatif,NaN,NaN,NaN
28,696f6b3b7a90c7b400bf72bc,"tag:blogger.com,1999:blog-4737517494033053260....",https://www.lexpress.mg/feeds/posts/default,BASKETBALL 3X3 - Fandriana célèbre sa champio...,NaT,Fandriana a vécu un moment historique en honor...,https://www.lexpress.mg/2026/01/basketball-3x3...,autre,neutre,NaN,NaN,NaN
29,696f6b3b7a90c7b400bf72bd,"tag:blogger.com,1999:blog-4737517494033053260....",https://www.lexpress.mg/feeds/posts/default,MALADIE CONTAGIEUSE - La Mpox progresse dans l...,NaT,Les cas de Mpox continuent d’augmenter. Malgré...,https://www.lexpress.mg/2026/01/maladie-contag...,politique,neutre,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2000,6994651a7cfce0fe5944045b,6a1b3f901f08438564d3bd8cc84539f06796cc50effcc4...,https://2424.mg/feed/,CATASTROPHE NATURELLE – Gezani s’éloigne défin...,NaT,"Antananarivo, 17 Février, 12h00 – Gezani ne re...",https://2424.mg/catastrophe-naturelle-gezani-s...,culture,neutre,rss,2026-02-17T12:54:12.182432,NaN
2001,6994655a7cfce0fe5944045c,626cd5b7d0f2ad2e493275a7bddf79e87d26a296dda862...,https://news.google.com/rss/search?q=Madagasca...,"Madagascar Avant Paris, le colonel Michaël Ran...",NaT,"Madagascar Avant Paris, le colonel Michaël Ran...",https://news.google.com/rss/articles/CBMiigJBV...,technologie,neutre,rss,2026-02-17T12:54:23.257726,NaN
2002,6994655f7cfce0fe5944045d,306977ce13fac6b3d4100ebb4f1c1a1fc1b8d14aee9e63...,https://news.google.com/rss/search?q=Madagasca...,Madagascar triple le prix de son visa électron...,NaT,Madagascar triple le prix de son visa électron...,https://news.google.com/rss/articles/CBMijgFBV...,autre,neutre,rss,2026-02-17T12:54:23.262172,NaN
2003,699465707cfce0fe5944045e,1bcb3682380a88cdcc49f586cc9176e31fc22a6d39cb2e...,https://news.google.com/rss/search?q=Madagasca...,Cyclone Gezani : le bilan grimpe à 38 morts à ...,NaT,Cyclone Gezani : le bilan grimpe à 38 morts à ...,https://news.google.com/rss/articles/CBMikwFBV...,autre,neutre,rss,2026-02-17T12:54:23.275604,NaN
2004,699465737cfce0fe5944045f,1c632fe7b422d2612816944d687632d65ba32ebcf51b9a...,https://news.google.com/rss/search?q=Madagasca...,Point de situation N°5 - Cyclone Tropical Inte...,NaT,Point de situation N°5 - Cyclone Tropical Inte...,https://news.google.com/rss/articles/CBMiugFBV...,autre,positif,rss,2026-02-17T12:54:23.278506,NaN

In [11]:
df["date_publication"] = df["date_publication"].dt.strftime("%Y-%m-%dT%H:%M:%SZ")

In [12]:
df["date_publication"].head(10)

0    2026-01-20T05:36:32Z
1    2026-01-20T05:31:21Z
2    2026-01-19T05:35:00Z
3    2026-01-19T05:00:00Z
4    2026-01-19T04:00:00Z
5    2026-01-17T06:36:00Z
6    2026-01-17T06:35:49Z
7    2026-01-17T06:35:38Z
8    2026-01-16T06:35:00Z
9    2026-01-16T06:32:53Z
Name: date_publication, dtype: object

In [13]:
df["date_originale"] = df["date_publication"]

In [14]:
df[["date_originale", "date_publication"]].head(20)

          date_originale      date_publication
0   2026-01-20T05:36:32Z  2026-01-20T05:36:32Z
1   2026-01-20T05:31:21Z  2026-01-20T05:31:21Z
2   2026-01-19T05:35:00Z  2026-01-19T05:35:00Z
3   2026-01-19T05:00:00Z  2026-01-19T05:00:00Z
4   2026-01-19T04:00:00Z  2026-01-19T04:00:00Z
5   2026-01-17T06:36:00Z  2026-01-17T06:36:00Z
6   2026-01-17T06:35:49Z  2026-01-17T06:35:49Z
7   2026-01-17T06:35:38Z  2026-01-17T06:35:38Z
8   2026-01-16T06:35:00Z  2026-01-16T06:35:00Z
9   2026-01-16T06:32:53Z  2026-01-16T06:32:53Z
10  2026-01-16T05:50:01Z  2026-01-16T05:50:01Z
11  2026-01-15T05:38:48Z  2026-01-15T05:38:48Z
12  2026-01-15T04:00:00Z  2026-01-15T04:00:00Z
13  2026-01-15T03:00:00Z  2026-01-15T03:00:00Z
14  2026-01-14T05:25:15Z  2026-01-14T05:25:15Z
15  2026-01-14T03:00:00Z  2026-01-14T03:00:00Z
16  2026-01-13T05:33:24Z  2026-01-13T05:33:24Z
17  2026-01-13T04:00:00Z  2026-01-13T04:00:00Z
18  2026-01-12T06:40:50Z  2026-01-12T06:40:50Z
19  2026-01-12T04:00:00Z  2026-01-12T04:00:00Z

In [15]:
df[df["date_originale"].str.contains(",", na=False)][
    ["date_originale", "date_publication"]
]

Empty DataFrame
Columns: [date_originale, date_publication]
Index: []

In [16]:
df[df["date_publication"].isna()]

,_id,id_article,source,titre,date_publication,contenu,url,categorie,sentiment,source_type,created_at,sentiment_score,date_originale
25,696f6b3b7a90c7b400bf72b9,"tag:blogger.com,1999:blog-4737517494033053260....",https://www.lexpress.mg/feeds/posts/default,POURSUITE JUDICIAIRE - Le général Ravalomanana...,NaN,L’ancien président du Sénat et l’ancienne mini...,https://www.lexpress.mg/2026/01/poursuite-judi...,politique,negatif,NaN,NaN,NaN,NaN
26,696f6b3b7a90c7b400bf72ba,"tag:blogger.com,1999:blog-4737517494033053260....",https://www.lexpress.mg/feeds/posts/default,CCI IVATO - Le colonel Randrianirina rassure l...,NaN,Le Chef de l’État a donné le coup d’envoi des ...,https://www.lexpress.mg/2026/01/cci-ivato-le-c...,politique,neutre,NaN,NaN,NaN,NaN
27,696f6b3b7a90c7b400bf72bb,"tag:blogger.com,1999:blog-4737517494033053260....",https://www.lexpress.mg/feeds/posts/default,TÉLÉCOMMUNICATIONS - Réforme législative en v...,NaN,Le gouvernement prépare un décret d’applicatio...,https://www.lexpress.mg/2026/01/telecommunicat...,politique,negatif,NaN,NaN,NaN,NaN
28,696f6b3b7a90c7b400bf72bc,"tag:blogger.com,1999:blog-4737517494033053260....",https://www.lexpress.mg/feeds/posts/default,BASKETBALL 3X3 - Fandriana célèbre sa champio...,NaN,Fandriana a vécu un moment historique en honor...,https://www.lexpress.mg/2026/01/basketball-3x3...,autre,neutre,NaN,NaN,NaN,NaN
29,696f6b3b7a90c7b400bf72bd,"tag:blogger.com,1999:blog-4737517494033053260....",https://www.lexpress.mg/feeds/posts/default,MALADIE CONTAGIEUSE - La Mpox progresse dans l...,NaN,Les cas de Mpox continuent d’augmenter. Malgré...,https://www.lexpress.mg/2026/01/maladie-contag...,politique,neutre,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2000,6994651a7cfce0fe5944045b,6a1b3f901f08438564d3bd8cc84539f06796cc50effcc4...,https://2424.mg/feed/,CATASTROPHE NATURELLE – Gezani s’éloigne défin...,NaN,"Antananarivo, 17 Février, 12h00 – Gezani ne re...",https://2424.mg/catastrophe-naturelle-gezani-s...,culture,neutre,rss,2026-02-17T12:54:12.182432,NaN,NaN
2001,6994655a7cfce0fe5944045c,626cd5b7d0f2ad2e493275a7bddf79e87d26a296dda862...,https://news.google.com/rss/search?q=Madagasca...,"Madagascar Avant Paris, le colonel Michaël Ran...",NaN,"Madagascar Avant Paris, le colonel Michaël Ran...",https://news.google.com/rss/articles/CBMiigJBV...,technologie,neutre,rss,2026-02-17T12:54:23.257726,NaN,NaN
2002,6994655f7cfce0fe5944045d,306977ce13fac6b3d4100ebb4f1c1a1fc1b8d14aee9e63...,https://news.google.com/rss/search?q=Madagasca...,Madagascar triple le prix de son visa électron...,NaN,Madagascar triple le prix de son visa électron...,https://news.google.com/rss/articles/CBMijgFBV...,autre,neutre,rss,2026-02-17T12:54:23.262172,NaN,NaN
2003,699465707cfce0fe5944045e,1bcb3682380a88cdcc49f586cc9176e31fc22a6d39cb2e...,https://news.google.com/rss/search?q=Madagasca...,Cyclone Gezani : le bilan grimpe à 38 morts à ...,NaN,Cyclone Gezani : le bilan grimpe à 38 morts à ...,https://news.google.com/rss/articles/CBMikwFBV...,autre,neutre,rss,2026-02-17T12:54:23.275604,NaN,NaN
2004,699465737cfce0fe5944045f,1c632fe7b422d2612816944d687632d65ba32ebcf51b9a...,https://news.google.com/rss/search?q=Madagasca...,Point de situation N°5 - Cyclone Tropical Inte...,NaN,Point de situation N°5 - Cyclone Tropical Inte...,https://news.google.com/rss/articles/CBMiugFBV...,autre,positif,rss,2026-02-17T12:54:23.278506,NaN,NaN